### ISSUE TITLE
Got error when run demo

### ISSUE THREAD

**Issue by wuwenxuan0226** [NVIDIA-AI-IOT/CUDA-PointPillars#11]
Hi,
I use
jetson nano 2 gb
Jetpack 4.6
CUDA 10.2
tensorrt 8.0
onnx 1.8

After compling, I run the demo, got error:
GPU has cuda devices: 1
----device id: 0 info----
GPU : NVIDIA Tegra X1
Capbility: 5.3
Global memory: 1979MB
Const memory: 64KB
SM in a block: 48KB
warp size: 32
threads in a block: 1024
block dim: (1024,1024,64)
grid dim: (2147483647,65535,65535)

Building TRT engine.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:9: Message type “onnx2trt_onnx.ModelProto” has no field named “version”.
trt_infer: ModelImporter.cpp:682: Failed to parse ONNX model from file: …/…/model/pointpillar.onnx
: failed to parse onnx model file, please check the onnx version and trt support op!

So can you tell me how to solve this error or which version of onnx do you use?

**Comment by daniel-dsouza** [comment]
@wuwenxuan0226 Please check the file `model/pointpillar.onnx`, and confirm that git-lfs downloaded the actual binary 19 MB file - if you open the file and see only human readable text, git-lfs didn't download it.

**Comment by wuwenxuan0226** [comment]
Hi,
Thanks for the reply. Now I can run it.
Many thanks.
