### ISSUE TITLE
calculate offset in the file which named preprocess_kernels.cu

### ISSUE THREAD

**Issue by liveforday** [NVIDIA-AI-IOT/CUDA-PointPillars#20]
at line 323 of `preprocess_kernels.cu`, the code calcuate offset.

```
//calculate offset
float x_offset = voxel_x / 2 + cordsSM[pillar_idx_inBlock].w * voxel_x + range_min_x;
float y_offset = voxel_y / 2 + cordsSM[pillar_idx_inBlock].z * voxel_y + range_min_y;
float z_offset = voxel_z / 2 + cordsSM[pillar_idx_inBlock].y * voxel_z + range_min_z;
```
I think the `w`  means intensity，
when calcuate x_offset, why  `voxel_x` multiply by `cordsSM[pillar_idx_inBlock].w`, not `cordsSM[pillar_idx_inBlock].x`
when calcuate y_offset, why  `voxel_y` multiply by `cordsSM[pillar_idx_inBlock].z`, not `cordsSM[pillar_idx_inBlock].y`
when calcuate z_offset, why  `voxel_z` multiply by `cordsSM[pillar_idx_inBlock].y`, not `cordsSM[pillar_idx_inBlock].z`

**Comment by minwim** [comment]
why
