### ISSUE TITLE
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

### ISSUE THREAD

**Issue by iloveai8086** [NVIDIA-AI-IOT/CUDA-PointPillars#28]
i use tenrorrt8.4 and when i am running ./demo ,Building TRT engine: there are some errors:
Building TRT engine.
trt_infer: Could not register plugin creator -  ::PillarScatterPlugin version 1
trt_infer: parsers/onnx/ModelImporter.cpp:780: While parsing node number 4 [ScatterBEV -> "479"]:
trt_infer: parsers/onnx/ModelImporter.cpp:781: --- Begin node ---
trt_infer: parsers/onnx/ModelImporter.cpp:782: input: "403"
input: "coords"
input: "params"
output: "479"
name: "onnx_graphsurgeon_node_0"
op_type: "ScatterBEV"
trt_infer: ModelImporter.cpp:751: --- End node ---
trt_infer: ModelImporter.cpp:754: ERROR: builtin_op_importers.cpp:4951 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
: failed to parse onnx model file, please check the onnx version and trt support op!
How can i fix the problem?

**Comment by acburigo** [comment]
I'm experiencing something similar. What solved your issue?
