### ISSUE TITLE
parse onnx model wrong

### ISSUE THREAD

**Issue by zhouliuer** [NVIDIA-AI-IOT/CUDA-PointPillars#31]
trt_infer: 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::35] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 0, Serialized Engine Version: 97)
trt_infer: 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)

**Comment by byte-deve** [comment]
You may need to rebuild the engine, please remove the original engine file under /model and retry.

**Comment by zhouliuer** [comment]
编译版本不一致引起
