### ISSUE TITLE
When I did the cmake .. && make -j64 and those error came out, is there anyone know how to fix this?

### ISSUE THREAD

**Issue by BarryLoveBerry** [NVIDIA-AI-IOT/CUDA-PointPillars#32]
![image](https://user-images.githubusercontent.com/84859347/164961001-4d4b1e90-db1c-4c80-ae5f-2362920d99c0.png)

**Comment by BarryLoveBerry** [comment]
I changed the procreated to public, the compile finished and it works. but I am not sure, whether it causes any other problems.

**Comment by dk-liang** [comment]
I meet the same problem, could you please tell me how to solve it?

**Comment by BarryLoveBerry** [comment]
> I meet the same problem, could you please 
tell me how to solve it?

e.g For context_ you can find it in the NvinferRuntime.h, and change the protected to public, that's what I did to fix the error


![image](https://user-images.githubusercontent.com/84859347/165696778-070127b9-5126-404a-8a1a-6885258e4940.png)

**Comment by byte-deve** [comment]
It comes from the earlier TRT API.
You can refer to: https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars/issues/33#issuecomment-1111113025

BR
Tony

**Comment by meanmee** [comment]
Is it possible to run on Cuda10.2 with Tensorrt7 now? with the recent codes.
