### ISSUE TITLE
 error: ‘virtual nvinfer1::IExecutionContext::~IExecutionContext()’ is protected within this context

### ISSUE THREAD

**Issue by dk-liang** [NVIDIA-AI-IOT/CUDA-PointPillars#33]
When I run:
`cmake .. && make -j8`

it shows:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/23117298/165528194-88b11704-3bc1-4c67-b634-315dd7d41c69.png">

Does anyone know how to fix it?

**Comment by dk-liang** [comment]
Thanks

**Comment by Charlie-lusie** [comment]
> Hi @dk-liang,
> 
> Looks like you're using earlier TRT version. Please try to replace [pointpillar.cpp#L30](https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars/blob/main/src/pointpillar.cpp#L30) [pointpillar.cpp#L31](https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars/blob/main/src/pointpillar.cpp#L31) with:
> 
> ```
>   context_->destroy();
>   engine_->destroy();
> ```
> 
> BR Tony

same problem and solved. Thank you.
